#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: App\Controller\BlogController::index

add_article:
  path: /add
  controller: App\Controller\BlogController::add

show_article:
  path: /articles/{id}
  controller: App\Controller\BlogController::show
  requirements: 
    id: '\d+'

edit_article:
  path: /edit/{id}
  controller: App\Controller\BlogController::edit
  requirements: 
    id: '\d+'

remove_article:
  path: /remove/{id}
  controller: App\Controller\BlogController::remove
  requirements: 
    id: '\d+'

admin_articles:
  path: /admin/articles
  controller: App\Controller\BlogController::lists

admin_users:
  path: /admin/users
  controller: App\Controller\UserController::index

user_remove:
  path: /remove/{id}
  controller: App\Controller\UserController::remove
  requirements: 
    id: '\d+'